# Generated by Django 5.1.4 on 2026-06-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funnellead_delivery_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnellead',
            name='delivery_preference',
            field=models.CharField(blank=True, choices=[('mobile', 'Servizio Mobile'), ('workshop', 'Servizio in Sede (Riazzino)')], max_length=20, verbose_name='Preferenza di appuntamento'),
        ),
    ]
